version: "3"

services:
  php:
    build:
      context: .
    cap_add:
      - SYS_ADMIN
    volumes:
      - ./:/var/www/html
  web:
    image: nginx:1.23
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - .docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
  db:
    image: postgres:15.1
    restart: unless-stopped
    environment:
      POSTGRES_USER: "${DB_USERNAME}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_DB: "${DB_DATABASE}"
    volumes:
      - pgsqldata:/var/lib/postgresql
    ports:
      - 5432:5432
  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 8080:8080
  redis:
    image: redis:7
    volumes:
      - redisdata:/data

volumes:
  pgsqldata:
  redisdata:
